#include "include/util/Array.hpp"
#include "include/util/Entry.hpp"
#include "include/util/Queue.hpp"
#include "include/util/Stack.hpp"
/*
#include "include/machine/State.hpp"
#include "include/machine/Transition.hpp"
#include "include/machine/Machine.hpp"
#include "include/machine/FiniteStateMachine.hpp"
#include "include/machine/TuringMachine.hpp"

// ==============================================


#include "src/machine/State.cpp"
#include "src/machine/Transition.cpp"
#include "src/machine/Machine.cpp"
#include "src/machine/FiniteStateMachine.cpp"
#include "src/machine/TuringMachine.cpp"
*/